# DATA 607 - Project # 3

### Vladimir Nimchenko


```{r}
library(tidyr)
library(dplyr)
```

read in the contents of the file to the data set and view the data set.
```{r}
glassdoor <- read.csv("https://raw.githubusercontent.com/johnnydrodriguez/data607_project3/main/glassdoor_2021.csv", header = TRUE)
# view the dataset
View(glassdoor)
```

 Tidy/Transform data from the glass door data and create "Company" data frame.
```{r}
# create the Company data frame from the glass door data
Company <-select(glassdoor, c('index','Rating', 'Company.Name','Location','Headquarters','Size','Founded','Type.of.ownership','Industry','Sector','Revenue','Competitors','company_txt','Age'))

# Change the "index" column to "CompanyID"
colnames(Company)[colnames(Company)== "index"] <-"CompanyID"

# Change the "Rating" column to "Company_Rating"
colnames(Company)[colnames(Company)== "Rating"] <-"Column_Rating"

# Change the "Company.Name" column to "Company_Name"
colnames(Company)[colnames(Company)== "Company.Name"] <-"Company_Name"

# Change the "Headquarters" column to "HQ_Address"
colnames(Company)[colnames(Company)== "Headquarters"] <-"HQ_Address"

# Change the "Type.of.ownership" column to "type_of_ownership"
colnames(Company)[colnames(Company)== "Type.of.ownership"] <-"type_of_ownership"

# Change the "Age" column to "Company_Age"
colnames(Company)[colnames(Company)== "Age"] <-"Company_Age"

#view the Company data frame
View(Company)

```

Tidy/Transform data from the glass door data and create "Jobs" data frame.
```{r}
# create the Company data frame from the glass door data
Jobs <-select(glassdoor, c('index','Job.Title', 'Salary.Estimate','Job.Description','Hourly','Lower.Salary','Upper.Salary','Avg.Salary.K.','Job.Location','job_title_sim','seniority_by_title','Degree'))

# Change the "index" column to "JobID"
colnames(Jobs)[colnames(Jobs)== "index"] <-"JobID"

# Change the "Job.Title" column to "Job_Title"
colnames(Jobs)[colnames(Jobs)== "Job.Title"] <-"Job_Title"

# Change the "Salary.Estimate" column to "Salary_Estimate"
colnames(Jobs)[colnames(Jobs)== "Salary.Estimate"] <-"Salary_Estimate"

# Change the "Job.Description" column to "Job_Description"
colnames(Jobs)[colnames(Jobs)== "Job.Description"] <-"Job_Description"

# Change the "Lower.Salary" column to "Lower_Salary(K)"
colnames(Jobs)[colnames(Jobs)== "Lower.Salary"] <-"Lower_Salary(K)"

# Change the "Upper.Salary" column to "Upper_Salary(K)"
colnames(Jobs)[colnames(Jobs)== "Upper.Salary"] <-"Upper_Salary(K)"

# Change the "Avg.Salary.K." column to "Avg_Salary(K)"
colnames(Jobs)[colnames(Jobs)== "Avg.Salary.K."] <-"Avg_Salary(K)"

# Change the "Job.Location" column to "Job_Location"
colnames(Jobs)[colnames(Jobs)== "Job.Location"] <-"Job_Location"

# View the Jobs data frame
View(Jobs)

```

Tidy/Transform data from the glass door data and create "Tech" data frame. Filter for and Add "R" and "API" technology
```{r}

# create the Tech data frame from the glass door data (include job.description field for filtering)
Tech <-select(glassdoor, c("index","Job.Description","Python","spark","aws","excel","sql","sas","keras","pytorch","scikit","tensor","hadoop","tableau","bi","flink","mongo","google_an"))

# Change the "index" column to "TechID"
colnames(Tech)[colnames(Tech)== "index"] <-"TechID"

#Add columns for R and ETL technologies 

colnames(Tech)[17:18] <- c("R", "ETL")


# filter for "R" Technology in Job Description field, 1 if exists 0 if doesn't
Tech <- Tech %>%
  mutate(R = ifelse(Tech$Job.Description == "R%", "1", "0"))
  
 # filter for "ETL" Technology in Job Description field, 1 if exists 0 if doesn't
Tech <- Tech %>%
  mutate(ETL = ifelse(Tech$Job.Description == "ETL%", "1", "0"))
  

  View(Tech)
  
 
  


```

